version: '3.8'
services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - '9000:9000'
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
networks:
    default:
        name: webnet