version: '3.8'
services:
  dowellspeedtest-backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default
  dowellspeedtest-frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - dowellspeedtest-backend
networks:
  webnet:
    external: true
    name: webnet